@HWYDotNetTrainingBatch1.Assigned.DreamDictionary.WebApi_HostAddress = http://localhost:5095

GET {{HWYDotNetTrainingBatch1.Assigned.DreamDictionary.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
